tectonic-typesetting/tectonic

- src/cli_driver.rs
This commit changes the condition that decides whether bibtex is run to
finding `\bibdata` in the aux file (was `\citation` and `\bibcite`).
Since bibtex exits with an error if it does not find `\bibdata` anyway,
this avoids running bibtex unecessarily when for instance amsrefs is
used to process the bibliography.
I also replaced `find(...).count() > 0` by `find(...).next().is_some()`: no need to go through the whole file, stop at the first match.
> Support amsrefs

- dist/arch/PKGBUILD
This has been discussed in issue #4. Including the PKGBUILD in this
repository has the benefit of versioning it alongside the code, and
eventually pushing it to the AUR as part of the continuous integration
pipeline. -- Alexander Bauer
> dist: include PKGBUILD from the AUR

- build.rs
This is really only a convenience for developers: there is not need to recompile the C/C++ code on every unrelated change in the repo.
> Rerun build.rs only on changes in the tectonic/ dir

- tectonic/xetexini.c
- This breaks all tests, because expected filenames no longer match the ones that are actually written. @pkgw I would appreciate your input on how to fix this, or what should be done about it.
- There was originally a test added in this PR for the behavior, but it failed even after the change was made (and not for the quoting reason.) I don't know what was wrong with it, but a better test should be written instead.
For my notes while developing this, see my comments in #36.
> Handle filenames with spaces

- .travis.yml
- dist/arch/deploy.sh
This uses Travis’s automatic deploy feature. Everytime a new version is tagged, the PKGBUILD file along with updated metadata will be uploaded to AUR.
Decrypting the private key was moved to the `before_deploy` stage, to limit the possibility of the key leaking.
Closes: #54
> Deploy releases to AUR automatically

- src/io/local_cache.rs
- After moving new cache files to their final destination, set their
permissions to have `readonly` set `true`.
- This uses `fs::set_permissions` rather than the suggested
``fs::File::set_permissions`, because the latter would require the final
file to be open. We cannot change the permissions on the tempfile in
this way, because `mkstemp::TempFile` doesn't have the same
`set_permissions` method.
Close #14
> Make cached bundle files readonly

- src/io/memory.rs
- src/io/mod.rs
- Only paths that are valid UTF8 are normalized.
- `std::path::{Path,PathBuf}` are not used to normalize in a system
independent way on Unix/Windows.
- LaTeX identifies OS by testing if `./texsys.aux` exists. This file
is created as `texsys.aux`. Without normalization, OS is
misidentified and filename parsing in LaTeX code then produces wrong
results. (See #50). This fixes the behavior (cache needs to be
rebuilt).
Note: Normalization currently does not handle path prefix on Windows, but this can be added later (paths on Windows are hard, need to explore what is reasonable).
> Fix #50: Normalize paths in MemoryIo

- Cargo.lock
- Cargo.toml
- tests/executable.rs
- tests/executable/test space.tex
The `tests/executable.rs` module includes tools for running the built
executable on a temporary directory, and for copying resources into the
temporary directory easily.
This will more easily let us reproduce reported issues, and test for
them automatically to prevent regressions.
This includes a regression test for #36
> tests: write executable and regression testing suite

- tectonic/bibtex.c
* Set the value of MAX_STRINGS to 15000. It turns out 10000 was not
enough to cleanly build the example mentioned in #81 using
(https://github.com/cryptobib/export_crossref/blob/118d812c4e1e8c462d3b1f226c02b9b1c6e4b505/abbrev0.bib).
* Fixes #79
Signed-off-by: mr.Shu <mr@shu.io>
> update: Update MAX_STRINGS value

- src/io/itarbundle.rs
* Add clearer message which clearly mention that the issues are not
caused by Tectonic, as per #51.
Signed-off-by: mr.Shu <mr@shu.io>
> update: Clearer message on network failure

- tests/executable.rs
- tests/executable/subdirectory/content/1.tex
- tests/executable/subdirectory/relative_include.tex
This PR adds a failing test case for issue #31. The test case is prefixed with a reasonably specific `should_panic` decorator, and is noted with a `// FIXME` referring to issue #31. When that issue is fixed, this test case will begin to fail (because it will no longer panic) and the directive can be removed.
I would prefer that this test didn't simply succeed, but gave an "expected failure"-type annotation in the results, like PyTest does. I don't know that this behavior is possible in the current state of Cargo testing.
> Reproduce #31

- tectonic/dpx-tfm.c
Triggered by #93, although I've since decided that it was only triggered erroneously.
This code loads Omega Font Metrics, which are a special metrics format invented for Omega, which was an early Unicode-enabled TeX engine.
> Change xdvipdfmx's OFM-loading code to use the Rust I/O subsystem

- src/engines/mod.rs
Fixes a regression caused by 7c2e4e622dde666a038154a9c925829e309a988f, for instance for `tests/xenia/paper.tex`.
Specifically, now tectonic tries to add default file format extensions only if the requested file does **not** have an extension already.
As I mentioned in #93, I believe that tectonic should not change the extension of files requested by a tex code, for instance return `natbib.sty` instead of `natbib.cfg`.
I also cleaned up the code to minimize allocations.
> Do not change the extension of files requested by the engine.

- src/io/local_cache.rs
This partially addresses #74 without actually changing the manifest format.
Now the lines in the manifest are split from the end (`rsplitn`) into exactly three pieces and only on
spaces (' ').
This allows filenames to have spaces in their names.
A sanity check has been added to not insert files with newline characters in their names. (I guess to prevent the potential to doctor a manifest line by crafting a file name).
Question: Is it worth inserting files with names that are not valid unicode, i.e. [use `to_string_lossy`](https://github.com/rekka/tectonic/blob/82269bbab803450b9d862b0e677f386a7fad2221/src/io/local_cache.rs#L179)? This record is then useless anyway because it will not match the original file.
> A more robust parsing of the manifest

- src/cli_driver.rs
- tests/executable.rs
This implements what is, I believe, the expected behavior of `--keep-logs`: Even if the xetex engine errors out, the logs are saved. This matches the tex standard and has at least two uses:
- Sometimes it is necessary to inspect the logs to understand why an error occurred.
- Editors, for instance `vim` with `vim-latex`, use the logs to locate errors and warnings.
A simple test is also provided.
I basically just extracted the code in `run` method that saves the outputs, etc., into `write_files` and added a parameter `only_logs`.
> Keep logs on error if --keep-logs provided

- tectonic/constants.h
- tectonic/xetex0.c
- Prefix is `MOV_`.
- Resolves the collision of `Z_OK` with a constant defined in
`zlib.h` as mentioned in #98 .
> Prefix TeX (Y|YZ|Z|D)_(OK|NONE|SEEN|FIXED) constants

- src/cli_driver.rs
- tests/executable.rs
> Add an option to specify the output directory

- src/engines/mod.rs
- src/engines/tex.rs
Fixes compilation on some targets where c_char != i8.
> Use libc::c_char when appropriated

- src/io/hyper_seekable.rs
- src/io/itarbundle.rs
- src/io/mod.rs
I've tried to keep the heuristic general and avoid false-negatives as it only interferes if the last segment of the URL doesn't contain a `.`
(This will separates hash-like URLs from ones that contain a file extension)
Closes #113
> Redirection heuristic for #113

- Cargo.lock
- Cargo.toml
Since we have lots of C code (splitted in many files), it makes sense
to build the code in parallel to reduce compilation time.
> enable gcc-rs parallel feature

- build.rs
unicode headers used in the C++ code use such types.
See #125
> build.rs: add -std=c++14 to have char16_t and similar defined

- Cargo.lock
- Cargo.toml
- build.rs
It allows us to remove our own flag_if_supported function.
> update to the latest version of gcc to use flag_if_supported

- .travis.yml
- build.rs
It looks like the Linux CI builds are a lot faster (7 minutes with crates cached) so I've moved the builds on Rust nightly and beta to Linux.
In the future it might be interesting to explore different `gcc`/`clang` builds.
This resolves #128.
> Add Linux in Travis CI

- tectonic/bibtex.c
These now match the current values that are used in TeXLive installations, to the best of my ability. Yes, this patch was motivated because I exceeded the previous values in one of my documents.
> tectonic/bibtex.c: increase size of various bibtex buffers

- build.rs
A bunch of functions like `strcasecmp` are only available in `glibc`.
This is the major source of warnings (about implicit function declarations).
> Target GNU C dialect

- .travis.yml
- tests/executable.rs
Locally `cargo-kcov` reports about 50% coverage with executable tests disabled. Let's see if this dramatically boost the coverage rate.
> Let `cargo-kcov` figure it out

- .circleci/config.yml
- .circleci/inner-build.sh
- .circleci/outer-build.sh
- build.rs
This is kind of ludicrous, but as far as I can tell the only free way to do this is to use QEMU to run the build inside a synthetic PowerPC CPU. It took a long time to make this work, which was probably not the best use of my time, but here we are!
> Set up CI to test and run Tectonic on a big-endian architecture

- src/cli_driver.rs
- src/engines/mod.rs
- src/io/local_cache.rs
- tectonic/xetexini.c
- tests/executable.rs
- tests/formats.rs
- tests/tex-outputs.rs
- tests/trip.rs
The gzip decoder is really slow in debug mode.
Disabling the compression for format files results in a 2x speedup of `load_fmt_file` in release builds.
The difference in debug builds is more noticeable and makes `cargo test`-ing more pleasant on _delicate_ hardware (180s => 30s).
This also results format blobs of doubled size though. Clever tweaks to the format could probably save a bit more space and still be faster than general-purpose compression.
Especially in debug mode, I think this performance/file-size trade-off is worth it.
I guess this shouldn't break anything as the format-file-format isn't stable at all.
If there's a special purpose to the compression or you think the file size is more important, feel free to close the PR.
**EDIT**: 7ac7766b2375cdd76e56f5b7eb9fdbdee7b99fe4 …
> Store format file uncompressed

- src/cli_driver.rs
- src/io/mod.rs
- src/io/setup.rs
This is a first step towards [issue 172](https://github.com/tectonic-typesetting/tectonic/issues/172): moving CliIoSetup into the main crate (and documenting it, and making it public). If this approach seems ok, I'll also do the same for ProcessingSession.
> Make CliIoSetup public and rename it.

- tectonic/dpx-pdfdoc.c
- tectonic/dpx-pdfencrypt.c
- tectonic/dpx-spc_dvips.c
- tectonic/dpx-spc_tpic.c
- tectonic/dpx-truetype.c
- tectonic/xetex0.c
- tectonic/xetexd.h
- tectonic/xetexini.c
Further rationale in the commit messages. Attempting to address #173 in a helpful way.
> Emit user-facing warning if unable to represent a character in the current font

- .gitmodules
With a relative path, I can't add tectonic's git repository as a dependency in Cargo.toml; attempting to do so gives:
```
$ cargo build
Updating git repository `https://github.com/tectonic-typesetting/tectonic`
error: failed to load source for a dependency on `tectonic`                     
Caused by:
Unable to update https://github.com/tectonic-typesetting/tectonic
Caused by:
failed to update submodule `reference_sources`
Caused by:
invalid url `../tectonic-staging.git`: relative URL without a base
```
> Use an absolute path to reference_sources

- src/driver.rs
This makes some fields public, so that it's possible to get interesting
information out of IoEvents. Also, fixes the behaviour of
ProcessingSessionBuilder::output_dir to match its documentation (i.e.,
don't panic if the output_dir is not provided).
> Fix various small issues in driver module.

- .circleci/outer-build.sh
- build.rs
Based on https://github.com/harfbuzz/harfbuzz/blob/master/NEWS, this seems to be the first minor version that includes required OpenType math support.
Closes #199.
> build.rs: make requirement of harfbuzz >= 1.4 more explicit

- src/bin/tectonic.rs
- src/config.rs
- src/io/local_cache.rs
This is a preliminary pull request proposing to add a **new command line option**. I want to ask for feedback.
With this flag enabled, tectonic will only use resource files that are already stored in the local cache and will not try to fetch them from a web bundle.
Tectonic at the moment accesses the bundle file whenever a new file like a figure is added to a TeX document or a new TeX file is being compiled. In a majority of these cases, this is unnecessary because the files will not be found in the bundle anyway. Usually, this is not a big issue, but it can be annoying to deal with when the web bundle is not accessible. I believe there should be a way to ask tectonic not to try to fetch the unknown files.
This has at least 3 use cases:
* workaround for web bundle problems like #200 
* no …
> Add --only-cached/-C command line flag

- src/io/memory.rs
- Just return `OpenResult::NotAvailable`, matching the behavior of
xelatex.
Fixes #188.
> Do not panic on an empty filename in MemoryIo

- src/engines/mod.rs
- tectonic/core-bridge.c
- tectonic/core-bridge.h
Instead of panicking on failure, add a warning and return an error value
(if possible).
Closes #63.
However, these kinds of problems should probably result in a failure since they indicate an internal engine error.
> Fix #63: do not panic into C

- build.rs
- src/io/local_cache.rs
- tectonic/XeTeX_ext.c
- tectonic/core-bridge.h
- tectonic/dpx-dpxfile.c
- tectonic/dpx-pdffont.c
- tectonic/dpx-spc_dvips.c
- tectonic/dpx-system.h
- tectonic/internals.h
- tectonic/xetex0.c
- tectonic/xetexd.h
- tectonic/xetexini.c
At least, on my test rig. Will AppVeyor like it???
> Get the test suite running on Windows

- .gitignore
- Cargo.toml
- src/bin/tectonic.rs
- src/config.rs
- src/driver.rs
- src/engines/bibtex.rs
- src/engines/mod.rs
- src/engines/tex.rs
- src/engines/xdvipdfmx.rs
- src/io/setup.rs
- src/io/stdstreams.rs
- src/lib.rs
- src/status/mod.rs
- src/status/termcolor.rs
- src/test_util.rs
- tests/assets/tectonic-format-latex.tex
- tests/driver.rs
- tests/executable.rs
- tests/formats.rs
- tests/tex-outputs.rs
- tests/trip.rs
- tests/util/mod.rs
The front page of our API docs will now look way better! And the "executable" tests now have better behavior, not touching the local user's cache or the network.
> Add an all-in-one latex_to_pdf() function and sweet testing infrastructure

- CHANGELOG.md
- src/config.rs
As per https://github.com/tectonic-typesetting/tectonic/issues/131 , there have been problems with purl.org historically. The archive.org domain should have more reliable SSL certificate updates.
> src/config.rs: default to archive.org, not purl.org

- Cargo.toml
- README.md
- src/config.rs
- src/errors.rs
- src/lib.rs
This introduces the `confile_file` feature that is enabled by default. Disabling the feature allow building for musl targets.
> Make serde dependency optional

- tectonic/core-foundation.h
Some versions apparently do not #define PRId64 and friends unless you add a special triggering #define.
This fixes a problem discovered when trying to build 0.1.11 on conda-forge ([tectonic-feedstock #11](https://github.com/conda-forge/tectonic-feedstock/pull/14)).
> tectonic/core-foundation.h: fix build for certain versions of g++

- CHANGELOG.md
I first noticed this on the [releases page](https://github.com/tectonic-typesetting/tectonic/releases). Probably should be fixed there, too, if possible.
> Fix changelog grammar: "the code [...] mode [...] reusable" → "the code [...] has been made [...] reusable"

- .circleci/inner-build.sh
Running with the idea of trying to avoid threads, try adding "-C codegen-units=1" to $RUSTFLAGS.
> .circleci/inner-build.sh: try harder to avoid QEMU hangs

- dist/travis.sh
Our Homebrew setup was breaking because `--with-graphite2` no longer worked.
> dist/travis.sh: harfbuzz now always includes graphite2

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/lib.rs
This is what's recommended. Mostly inspired by me worrying about multiple Dependabot PRs for every Serde bump.
> Drop explicit dep on serde_derive

- src/driver.rs
- src/engines/mod.rs
- src/engines/spx2html.rs
- src/io/filesystem.rs
- src/io/format_cache.rs
- src/io/itarbundle.rs
- src/io/local_cache.rs
- src/io/memory.rs
- src/io/mod.rs
- src/io/setup.rs
- src/io/stack.rs
- src/status/termcolor.rs
I started looking at [`clippy`](https://github.com/rust-lang/rust-clippy) output. There are a large number of warnings. Rather than do them all and have an overwhelming PR, I started with `redundant_field_names`.
I think it would be good to eventually add `cargo clippy` to CI, but, first, I'd like to get feedback on this bit of lint fixing.
> cargo clippy: fix redundant_field_names

- src/config.rs
Fixes [`needless_return`](https://rust-lang.github.io/rust-clippy/master/#needless_return)
> cargo clippy: fix needless_return

- src/engines/mod.rs
Fixes [`https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg`](https://rust-lang.github.io/rust-clippy/master/index.html#unit_arg)
> cargo clippy: fix unit_arg

- src/engines/spx2html.rs
Fixes [`len_zero`](https://rust-lang.github.io/rust-clippy/master/index.html#len_zero)
> cargo clippy: fix len_zero

- src/engines/spx2html.rs
Fixes [`unused_io_amount`](https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount)
Note that this change may affect your logic. But, considering you're not checking for the number of bytes written by `io::Write::write`, I'm guessing it's safe.
> cargo clippy: fix unused_io_amount

- src/engines/mod.rs
Fixes [`zero_ptr`](https://rust-lang.github.io/rust-clippy/master/index.html#zero_ptr)
> cargo clippy: fix zero_ptr

- src/bin/tectonic.rs
Fixes [`match_ref_pats`](https://rust-lang.github.io/rust-clippy/master/index.html#match_ref_pats)
> cargo clippy: fix match_ref_pats

- src/io/setup.rs
Fixes [`needless_lifetimes`](https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes)
> cargo clippy: fix needless_lifetimes

- src/engines/mod.rs
Fixes [`cast_lossless`](https://rust-lang.github.io/rust-clippy/master/index.html#cast_lossless)
> cargo clippy: fix cast_lossless

- src/engines/mod.rs
Don't warn about [`vec_box`](https://rust-lang.github.io/rust-clippy/master/index.html#vec_box).
> cargo clippy: allow vec_box

- tectonic/dpx-truetype.c
- tests/executable.rs
Inspired by #328 by @spl, but takes a different tack. The limitation with the other PR is that the header file didn't actually suppress the warnings on GCC! At the moment, I think it's just simpler to gate the pragmas by compiler explicitly.
This PR also includes a fix against a race condition in the test suite.
> Suppress unknown warnings on Clang, alternate version

- tests/executable.rs
- tests/util/mod.rs
- xdv/src/lib.rs
Okay, so now I've figured out how to `cargo clippy` the tests (and all other targets), and these are the results. The warning type fixes are broken down into separate commits. All changes are, I think, pretty innocent.
> cargo clippy tests

- dist/travis.sh
This causes Travis-CI to fail if `clippy` finds any warning lints. It will, of course, fail now, since there are warnings to be found. But if #351 and #352 are merged and this branch is updated, it will pass.
> Run clippy on Travis-CI

- .travis.yml
- dist/travis.sh
Use the Travis-CI [`homebrew` add-on](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos) to `brew install` packages on macOS.
Comments:
* This does not do a `brew update` since that slows down the build quite a bit.
* I don't think the `--force` flag is necessary for `brew install openssl`.
> Install Homebrew packages in .travis.yml

- dist/travis.sh
* Make the Travis-CI log easier to follow by reducing the noise:
- put more things behind folds
- put folds inside if-then blocks to avoid printing `'+ false'`, etc.
- make fold titles simpler and more consistent
- avoid printing the values already found in the printed env vars
* Document the `travis_fold` usage
> Neaten the dist/travis.sh presentation

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/driver.rs
- src/io/mod.rs
- tests/driver.rs
- tests/executable.rs
- tests/tex-outputs.rs
- tests/trip.rs
- xdv/src/lib.rs
It's only used in tests, but the tempdir crate has been deprecated here:
https://github.com/rust-lang-deprecated/tempdir
This updates the tests to use tempfile.
> replace usage of deprecated tempdir crate with tempfile.

- tectonic/bibtex.c
- tectonic/xetex-ext.c
- tectonic/xetex-ini.c
- tectonic/xetex-xetex0.c
- tests/tex-outputs/otf_basic.log
I missed a bit of pascal-like string handling in my refactoring PR: #165
---------------------------------------------
This is an example use-case for the regression tester (#397).
This comparison reveals the regression:
https://tt.ente.ninja/#/compare/v0.1.9-dirty/v0.1.10
This is the changeset for this PR:
https://tt.ente.ninja/#/compare/v0.1.11/fix-font-name-v0.1.11-276-g62ce204
This confirms that the regression was fixed:
https://tt.ente.ninja/#/compare/v0.1.9-dirty/fix-font-name-v0.1.11-276-g62ce204
_The differences in `CAG_D-17-00218_Edited.pdf` are not related._
> Fix an off-by-one in usages of the `name_of_file` variable.

- Cargo.lock
Roll up the Dependabot updates, as well as others.
> Cargo.lock: update many deps

- dist/docker/x86_64-alpine-linux-musl/setup_priv.sh
- dist/docker/x86_64-alpine-linux-musl/setup_unpriv.sh
Cuts down onthe noise when building the container for static binary
generation:
```
docker build -t tectonic-builder:v1 dist/docker/x86_64-alpine-linux-musl/
```
It would be nice to configure the options for `wget` instead of installing `curl`: https://github.com/rust-lang/rustup.rs/issues/1928
> supress some downloading progress output

- dist/docker/x86_64-alpine-linux-musl/README.md
* ran this on Docker for Mac 2.1.0 to produce a static binary that I
executed successfully on an Amazon Linux Instance
* Partially addresses #185. I think we would want to decide on whether
to automate this and when per https://github.com/tectonic-typesetting/tectonic/blob/master/dist/travis.sh#L272
> document using docker for cross compilation

- .gitignore
- README.md
- docs/book.toml
- docs/src/README.md
- docs/src/SUMMARY.md
- docs/src/project/README.md
- docs/src/project/fuzz.md
- docs/src/project/tectonic.md
- docs/src/resources/README.md
Start to resolve #62 and other documentation related issues.
I found this  [this rust subreddit discussion](https://www.reddit.com/r/rust/comments/7eohmt/whats_the_best_practice_for_documenting_a_rust/) about best practices for documentation. [Doxidize](https://steveklabnik.github.io/doxidize/index.html) seems like it could suit us well but [isn't ready for use](https://github.com/steveklabnik/doxidize/issues/116#issuecomment-421607742).
mdBook may not integrate as nicely with a crate but it seems like the community standard.
I started a preliminary structure but am sure we should establish the audience and then establish a suitable TOC.
> create an mdbook for documentation

- Cargo.lock
- Cargo.toml
There are three zip implementations being used in tectonic:
- from zip crate (libflate implemented in rust)
- from flate2 crate (miniz-sys implemented in c)
- zlib (native dependence in build.rs)
This PR make flate2 use zlib, removing the miniz-sys dependence. We also disable bzip2 feature from zip crate, I don't think it is being used. This reduces 93k from the final binary.
When (or if) https://github.com/mvdnes/zip-rs/pull/107 get merged, we can get rid of libflate dependence.
> Use libz-sys backend for flate2 and disable bzip2 for zip

- src/app_dirs.rs
We need to test `local_cache.rs` and `itarbundle.rs`. 0% coverage currently.
> Quickfix for #429 (make sure the cache dirs are created)

- src/driver.rs
I could not find this example so removed the line.
If the `cli_driver.rs` moved somewhere else I can instead update the text to that location.
> remove outdated documentation comment

- .appveyor.yml
- .gitattributes
- Cargo.lock
- Cargo.toml
- build.rs
- dist/docker/x86_64-alpine-linux-musl/Dockerfile
- src/app_dirs.rs
- src/config.rs
- tectonic/xetex-XeTeXFontMgr.cpp
- tectonic/xetex-XeTeXLayoutInterface.cpp
- tectonic/xetex-core.h
@crlf0710 added the ability to build using msvc with libraries from vcpkg. 
I'm not sure if it is useful to you, but vcpkg-rs 0.2.7 adds support for Linux and macOS so I enabled it for them also. (This does allow using the exact same versions of libraries across all platforms which may be of interest.) Windows (msvc) works for static and dynamic builds, and Linux and macOS work for static builds. Almost everything builds and passes tests, but on Windows, one of the doctests still fails the first time it is run.
This fixes the issue with the line endings in the test data getting changed to CRLF when it is checked out on Windows, by adding a `.gitattributes` file. This does not update an existing checkout so it is probably necessary to delete the `tests/` directory and check it out again to …
> fix checkouts of standing data for tests on Windows, enable vcpkg on macOS and Linux

- build.rs
- tectonic/teckit-Engine.cpp
- tectonic/teckit-cxx-Engine.h
There is no throw clause in the source code and Converter::Exception is never created, so I think this is dead code.
> Disable exceptions and rtti for C++ code

- dist/travis.sh
This should provide more context in a case of a test failure.
> Enable backtraces during Travis run

- Cargo.lock
#439 removes a line from `Cargo.lock`. This should be committed I believe.
> Commit updated Cargo.lock

- dist/build-mdbook.sh
- dist/force-push-tree.sh
- dist/travis.sh
See the main commit message for a bit of rationale. The best way I can see to graft multiple static HTML trees into the tectonic-typesetting.github.io URL family is to use helper repos with simple names that serve as targets for static HTML force-pushes.
Unfortunately this logic can only *really* be tested by merging to master, so if things look good that's what I'll do.
> Prototype infrastructure to publish the docs/ HTML

- docs/src/SUMMARY.md
- docs/src/cookbook/index.md
- docs/src/cookbook/vcpkg.md
Document how to use vcpkg to build tectonic on macOS.
Adapted the details from https://github.com/tectonic-typesetting/tectonic/pull/420.
> document building with vcpkg

- src/io/cached_itarbundle.rs
- src/io/format_cache.rs
- src/io/mod.rs
- src/io/zipbundle.rs
As observed in #452, a big chuck of runtime is spend computing sha256 digests. However, these are for the most part never used.
This pull request adds `InputHandle::read_only: bool` field and `fn
InputHandle::new_read_only` that sets this field to `true`. It indicates
that it is not possible to write into such file, for example, the format
file, the tar bundle or zip bundle, and so `InputHandle` does not need
to compute sha256 digest.
Saves 15--25% of tectonics runtime for a typical document.
On my machine, `tests/xenia/paper.tex` the run time is 1s vs 1.3s, and on a 30 pages tex file 1.9s vs. 2.2s.
> Do not compute the sha256 digest for read-only files

- Cargo.lock
- Cargo.toml
- src/bin/tectonic.rs
- src/driver.rs
- src/status/mod.rs
- tests/executable.rs
Per conversations [here](https://github.com/tectonic-typesetting/tectonic/issues/405#issuecomment-509207477) and in other issues.
I manually reviewed each of the flags but acceptance testing would be helpful.
- I decided to use the `FromStr` trait for parsing certain switches that end up as an enum. You can use enums [directly](https://github.com/TeXitoi/structopt/blob/master/examples/enum_in_args.rs) in structopt, but you need to wrap them in a clap macro. It changed the existing design too much and I hit a wall with some compiler errors so I took this approach.
- structopt seems to lowercase the `name` argument configuration. E.g. ` <input>    The file to process, or "-" to process the standard input stream"`
> use structopt for CLI argument parsing

- tectonic/bibtex.c
I've confirmed that the texlive sources have a space here.
Before this change, error messages looked like "Illegal end of database file---line 3 of filetest.bib"; this adds a space between "file" and "test.bib".
> Add a space in bibtex error messages.

- src/bin/tectonic.rs
- src/driver.rs
- src/engines/mod.rs
- src/engines/tex.rs
- src/engines/xdvipdfmx.rs
- src/io/cached_itarbundle.rs
- tectonic/core-bridge.c
- tectonic/core-bridge.h
- tectonic/dpx-dvipdfmx.c
- tectonic/dpx-dvipdfmx.h
- tectonic/dpx-pdfdoc.c
- tectonic/dpx-pdfencrypt.c
- tectonic/dpx-pdffont.c
- tectonic/dpx-pdfobj.h
- tectonic/xetex-ini.c
- tectonic/xetex-texmfmp.c
- tectonic/xetex-xetexd.h
- tests/tex-outputs.rs
This replaces dvipdfmx's `get_unique_time_if_given` by passing a 'current time' to the engines via the `build_date`config option.
> Introduce build_date engine parameter

- Cargo.lock
- Cargo.toml
- dist/travis.sh
- src/app_dirs.rs
- src/errors.rs
The toml crate is only needed when serialization feature is enabled, so it can be made optional.
i had to create dump errors to put in place of the toml errors in the error-chain setup.
This also tests building with --no-default-features.
> Make toml crate optional

- src/bin/tectonic.rs
- src/config.rs
- src/io/dirbundle.rs
- src/io/mod.rs
- src/io/zipbundle.rs
DirBundle allow reading bundle files from a directory. This is much faster than reading the files from a ZipBundle. For someone working offline this is good.
> Add DirBundle

- tectonic/bibtex.c
This fixes an issue I'm having with memory corruption when calling bibtex multiple times. I have some sample code demonstrating the problem in https://github.com/jneem/tectonic-bibtex-test. Before this patch, running that code reliably produces valgrind warnings (and occasionally crashes). After this patch, it doesn't.
> Zero memory upon allocation in bibtex.

- docs/src/cli/index.md
As mentioned #373, I started with just copying the output from `tectonic --help` into markdown. If you agree, I will document some more tips and other things that are now sort of hidden in old issues etc.
I don't understand where the option `--hide` would be used for, can you give an example?
> Start documenting cli options

- Cargo.lock
- Cargo.toml
- build.rs
- cfg_support/Cargo.toml
- cfg_support/src/lib.rs
Here is a first stab at #476
Test coverage in this library isn't complete, It's a little terrible.
It could probably be it's own crate instead of added as a subdir module.  
but i wanted to post for feedback before commiting to any API..
There is still some `#[cfg(...)]` stuff left in build.rs, but those are generally dealing with running host tools.  This doesn't currently implement cargo-feature checking, which seems to require it's own special mechanism.
> move target directed cfg! target checks to using a cfg_support module.

- Cargo.toml
- build.rs
Take 2 on Pr #473, built on top of #477 so that would need to go in first.
It only required a few minor changes, (bump to released cc-rs),
using let instead of const, and of a closure for profile_config instead of a local fn.
[comparison against PR 477](https://github.com/ratmice/tectonic/compare/cfg_support...ratmice:pr_473-take2?expand=1)
>  omit-frame-pointer and profile feature (take 2)

- .travis.yml
- RELEASE_PROCESS.md
- Most important: looks like we need to tweak the Travis config to get tagged release builds!
- Add V1 of the release process workflow. There are a lot of steps.
> Post-release tidying

- .appveyor.yml
- .circleci/config.yml
- .circleci/deploy.sh
- dist/travis.sh
It would be good if the Circle CI tests could upload build artifacts like the ones in Travis are now doing. This is a set of exploratory changes to try to enable that.
> .circleci: start investigating integration into the continuous-deployment workflow

- tectonic/bibtex.c
In the original bibtex.web, the default value for min_crossrefs is 2, not 0. Thia matches that behaviour.
The bibtex distributed with texlive also defaults to min_crossrefs = 2 (and it also makes it configurable at run-time, with a CLI arg, which this patch doesn't do).
> Set min_crossrefs to default to 2, not 0.

- tectonic/xetex-XeTeXLayoutInterface.cpp
- tectonic/xetex-xetex0.c
A leak is detected in Engine->shaperList. A simple and safe fix.
> Fixing memory leak of shaperList

- Cargo.lock
- Cargo.toml
- src/driver.rs
Hi!
This pr addresses issue #539 
- Paths and filenames are now quoted in backticks
- File sizes are now expressed in appropriate units (KiB/MiB)
| Before | After |
| --- | --- |
| Writing **file name.pdf** (47203 bytes) | Writing **\`file name.pdf\`** (46.10 KiB) |
When the output has size 0, the "Not writing **\`file name\`**: it would be empty" message also gets backticks.
This adds a new dependency (byte-unit) for expressing file sizes.
> Improve log formatting

- Cargo.toml
- cfg_support/Cargo.toml
- cfg_support/LICENSE
This for issue #565, assuming that you agreeable to that of course.
> Add a license to cfg support without the note about third party licenses.

- dist/arch/PKGBUILD
By default, cargo places build artifacts in a `target` directory in the root of the current workspace. This behaviour can be overridden through various means like ENV variables: https://doc.rust-lang.org/cargo/reference/config.html#buildtarget-dir
If that is the case, installation of the package will fail because the tectonic binary will not be in the path assumed by the `package` function.
We fix this by specifying the path of the `target` directory directly for the `build` and `check` functions.
> Specify target directory implied by the `package` function

- tectonic/xetex-xetex0.c
Inspired by a case where the message seemed to be saying `could not represent character "y" in $FONT` but it turned out that the character in question was a U+0443 CYRILLIC SMALL LETTER U.
> tectonic/xetex-xetex0.c: print out the hex of the lost char

- tectonic/xetex-errors.c
- tectonic/xetex-ini.c
- tectonic/xetex-xetexd.h
This is a followup of sorts to #574, and it turns out the async environment was totally unnecessary. In fact, this snippet is all that is necessary to trigger the segfault (the DejaVu Sans font needs to be installed):
```rust
use tectonic::latex_to_pdf;
fn main(){
for _ in 0..2 {
latex_to_pdf(r"\documentclass{article}
\usepackage{fontspec}
\setmainfont{DejaVu Sans}
\begin{document}
\invalidcommand{}
\end{document}");
}
}
```
This is a legacy issue, of sorts. Since XeTeX is meant to be used as an executable binary, it does not clean up its intermediate compilation data in case of a fatal failure: no further compilations will be tried and the OS will clear up the process' memory. However, tectonic uses the XeTeX as a library, and some variables get abandoned/leaked or its memory locations …
> Prevent segfault on latex compilation error

- tectonic/xetex-errors.c
- tectonic/xetex-ini.c
- tectonic/xetex-linebreak.c
- tectonic/xetex-math.c
- tectonic/xetex-output.c
- tectonic/xetex-pagebuilder.c
- tectonic/xetex-pic.c
- tectonic/xetex-shipout.c
- tectonic/xetex-xetex0.c
This is a followup of #625 that adds diagnostics to all places in xetex where errors or warnings are emitted (unless I've missed any). This doesn't add any to bibtex or dpx.
I've mainly looked for places
- which call functions that set `history` (mainly `begin_diagnostic()`)
- that have the "print file & line number" block which `error_here_with_diagnostic` replaces
- which call `error()` and related functions
> Add diagnostics where errors/warnings are emitted

- Cargo.lock
- Cargo.toml
- dist/azure-coverage.yml
- src/bin/tectonic.rs
- src/driver.rs
- src/status/mod.rs
- src/status/plain.rs
- src/status/termcolor.rs
- tests/executable.rs
#487 implements most of this but appears abandoned. This fixes some of the comments left on those changes.
> Finish PlainStatusBackend

- dist/azure-coverage.yml
- tests/executable.rs
It turns out that our tests of the built `tectonic` executable weren't gathering code coverage information about the code paths exercised in those tests. I *think* that it's not so hard to hack in some support to gather that information, so let's give it a try.
CC @ralismark @Mrmaxmeier 
xref: #636 assert-rs/assert_cmd#9
> tests: attempt to gather code coverage info in the executable tests

- Cargo.toml
- tectonic/dpx-cidtype0.c
The `if` statement inside the loop body could never succeed. Presuming that the `vertOriginYMetrics` are a sorted list, it looks like we need a `>=` condition.
Closes #639.
> tectonic/dpx-cidtype0.c: attempt to fix loop condition

- build.rs
This changes building with the vcpkg dep backend to emit the cargo metadata after tectonic's own in the same way that it does when using pkg-config.
> also emit cargo metadata after tectonic's own when using vcpkg

- src/bin/tectonic.rs
- src/status/mod.rs
- src/status/plain.rs
- src/status/termcolor.rs
This change in behavior was introduced in #636 with the genericization of the status backend. Add a new `report_error` method to recover the old behavior.
Closes #665.
> Don't print an empty "error:" line in the CLI

- Cargo.toml
- dist/azure-ci-cd.yml
- tectonic/xetex-texmfmp.c
Sigh, turning off vcpkg hid a build problem on Windows/MSVC (namely, no `sys/time.h`). It might be a simple fix, but I want to see if I can get something going in the CI to catch potential issues, since it looks like it will be a while before vcpkg is working again.
> Fix Windows/MSVC build failure

- tectonic/xetex-output.c
> tectonic/xetex-output.c: handle USV 0xFFFF in print()

- dist/arch/PKGBUILD.in
#690 fails without these dependencies.
I set them in Dockerfile manually, but I think this pr is the right way.
`gcc` is required for `proc-macro2`.
`pkg-config` is required for `rust-openssl`.
> Fix arch linux makedepends

- Cargo.toml
This adds support for building on an `aarch64-apple-darwin` machine using dependencies from `vcpkg`.
It updates `vcpkg` to the most recent commit - the `vcpkg` tree has pretty recently fixed building `graphite2` for `arm64-osx`. (I'm pretty sure the fix is that`vcpkg` now uses `cmake` 3.19 which sets `CMAKE_SYSTEM_PROCESSOR` correctly.)
> Add support for aarch64-apple-darwin building with vcpkg dep backend

- Cargo.lock
- Cargo.toml
- build.rs
- crates/bridge_graphite2/CHANGELOG.md
- crates/bridge_graphite2/Cargo.toml
- crates/bridge_graphite2/README.md
- crates/bridge_graphite2/build.rs
- crates/bridge_graphite2/src/lib.rs
- crates/dep_support/CHANGELOG.md
- crates/dep_support/Cargo.toml
- crates/dep_support/README.md
- crates/dep_support/src/lib.rs
- src/lib.rs
Add a "bridge" crate for graphite2. Unlike the flate2 bridge crate, here we need to use our existing dep-finding tools since there's no preexisting `graphite2-sys`, so break that code into its own support crate as well.
Note that we intentionally do *not* call this a `graphite2-sys` crate since we don't export any Rust types for graphite2. All we do is link to it and propagate the information about where to find the C headers. This will position us to vendor the library one day, though.
> Create a bridge crate for graphite2

- dist/arch/PKGBUILD.src.in
The src PKGBUILD previously forced a target directory of `./target`, presumably so that installation could copy the `tectonic` binary from `target`. It's preferable to let the target directory vary with `CARGO_TARGET_DIR` and then reach into `CARGO_TARGET_DIR` if defined when installing, because a shared target directory enables less cache duplication across rust programs and can decrease build time if dependencies are already cached.
> Support CARGO_TARGET_DIR in PKGBUILD

- Cargo.lock
- Cargo.toml
- build.rs
- crates/bridge_freetype2/CHANGELOG.md
- crates/bridge_freetype2/Cargo.toml
- crates/bridge_freetype2/README.md
- crates/bridge_freetype2/build.rs
- crates/bridge_freetype2/src/lib.rs
- src/lib.rs
- tectonic/xetex-core.h
As expected, we can't use the various preexisting freetype-sys crates (there are several) because they don't plug into our build framework the way that we need. For now.
> Add a FreeType2 bridge crate

- Cargo.lock
- Cargo.toml
- build.rs
- crates/bridge_icu/CHANGELOG.md
- crates/bridge_icu/Cargo.toml
- crates/bridge_icu/README.md
- crates/bridge_icu/build.rs
- crates/bridge_icu/src/lib.rs
- src/lib.rs
I was hoping to use `rust_icu_sys` here, since it prints out a Cargo line that we can use to find its C headers, but the currently released version requires nightly, has a build bug on my machine, and would add `bindgen` as a build-time dependency.
> crates/bridge_icu: add ICU bridge crate

- Cargo.lock
- Cargo.toml
- build.rs
- crates/bridge_freetype2/build.rs
- crates/bridge_graphite2/build.rs
- crates/bridge_harfbuzz/CHANGELOG.md
- crates/bridge_harfbuzz/Cargo.toml
- crates/bridge_harfbuzz/README.md
- crates/bridge_harfbuzz/build.rs
- crates/bridge_harfbuzz/src/lib.rs
- src/lib.rs
Last in the current push. Now that we have bridges for all of these system libraries, we can start pushing backwards and making it possible to vendor them.
> crates/bridge_harfbuzz: add this

- tectonic/xetex-XeTeXFontInst.cpp
- tectonic/xetex-XeTeXLayoutInterface.cpp
This is @Mrmaxmeier's #454 rebased onto current master. Now that we can vendor Harfbuzz, it's time to finally kill these warnings!
(Although if we do vendor harfbuzz, we get a new deprecation warning from it using a deprecated Graphite2 API call :-()
> tectonic: avoid deprecated harfbuzz apis

- Cargo.lock
- Cargo.toml
- docs/src/v2cli/build.md
- src/bin/tectonic/v2cli.rs
- src/document.rs
- tests/executable.rs
Fixes https://github.com/tectonic-typesetting/tectonic/issues/109
Adds the `--open` option to the `build` subcommand of the new v2 cli.
> Add open document option

- Cargo.lock
- Cargo.toml
- README.md
- crates/geturl/CHANGELOG.md
- crates/geturl/Cargo.toml
- crates/geturl/README.md
- crates/geturl/src/curl.rs
- crates/geturl/src/lib.rs
- crates/geturl/src/null.rs
- crates/geturl/src/reqwest.rs
- dist/azure-build-and-test-pkgconfig.yml
- dist/azure-build-and-test-vcpkg.yml
- dist/azure-ci-cd.yml
- dist/azure-generic-build.yml
- docs/src/howto/build-tectonic/index.md
- src/config.rs
- src/document.rs
- src/errors.rs
- src/io/cached_itarbundle.rs
- tests/executable.rs
Implementing @malbarbo's #525 with a sub-crate to isolate the HTTP backend API.
~Starting out as a draft, checking that we didn't break anything before adding the new `curl` backend.~
This will supersede #525 once it's ready.
> Allow choice of reqwest or curl for HTTP backend

- src/document.rs
Fixes #740.
One day we should get cleverer about this and provide the option of locking in a build date in a `Tectonic.lock` file, for *true* reproducibility ... but until that day, we should use the current time.
**Edit:** Note to self ... If we start providing options to insert Git commit info, which I think we should, we should provide a way to set the date from the Git commit timestamp.
> src/document.rs: set the build date to "now"

- README.md
As discussed in https://github.com/tectonic-typesetting/tectonic/issues/743 will add a reference to the setup tectonic github action
> Add setup-tectonic github action reference

- Cargo.lock
- crates/xdv/src/lib.rs
- src/document.rs
- src/io/memory.rs
> Fix some potential UB in tectonic_xdv, and cargo update

- Cargo.lock
- Cargo.toml
- src/bin/tectonic/main.rs
- src/bin/tectonic/v2cli.rs
- src/bin/tectonic/watch.rs
Fixes #719
This adds the `watch` subcommand, based off of `cargo-watch`. This design should allow for future addition of subcommands such as `check` or `format` which may run after or before a build stage or in place of one. It is very dumb at the moment and just watches all files in the current directory, besides the output `build` dir.
Tested that it works for me on a setup from `tectonic -X new`.
Haven't really got a good idea of how to go about testing this kind of thing but most of the work is done by the `watchexec` crate anyway.
> Add basic watching ability to v2 cli

- docs/src/ref/documents.md
- docs/src/ref/tectonic-toml.md
- src/document.rs
- src/errors.rs
- tests/executable.rs
This enables the use of preamble, index and postamble keys in an output.
These get built together to form the input buffer and default to the
current defaults too.
There isn't any fancy checking here as we defer it to the latex engine.
In theory this could enable injection but I'm not aware that would be a
concern at the moment.
Fixes https://github.com/tectonic-typesetting/tectonic/issues/745
> Tectonic.toml: preamble, index and postamble

- Cargo.lock
- crates/bridge_core/src/lib.rs
- crates/io_base/src/filesystem.rs
- tests/tex-outputs.rs
This PR addresses #754 and also touches things up for the new Rust release.
> Various updates

- dist/azure-coverage.yml
Trying to rework the arguments that we use so that the coverage analysis will be more robust to rearrangements of the source tree.
> dist/azure-coverage.yml: oh hey, let's unbreak coverage

- Cargo.lock
- Cargo.toml
- src/bin/tectonic/v2cli.rs
- src/bin/tectonic/watch.rs
The new watchexec changed its error type, I think, and our build broke. Require the new version, track changes to deprecated APIs, and work around the change.
Also update our deps in Cargo.lock in general.
> Fix build with watchexec 0.15

- src/bin/tectonic/compile.rs
- src/errors.rs
- Make the Clippy found in Rust 1.52.0 happy
- Update bundled Harfbuzz to the new 2.8.1 release
> Minor updates

- CARGO_README.md
- Cargo.toml
- README.md
- docs/src/getting-started/install.md
- docs/src/installation/index.md
Use the new "latest" link that avoids GitHub release confusion (#773). And copy over some package-manager instructions from the GitHub Pages website, which I'm planning to phase out.
> docs: update installation instructions

- dist/arch/PKGBUILD.src.in
- dist/azure-deployment-setup.yml
This is needed to get the vendored sources. This should address part of #776, I believe, although I'll need to issue a new release of `tectonic_bridge_harfbuzz` to verify.
> dist/azure-deployment-setup.yml: include submodules when checking out for deployment

- dist/arch/PKGBUILD.bin.in
- dist/arch/PKGBUILD.src.in
Hi, I am the package maintainer for the binary release of tectonic on the AUR.
I looked back at the package and upstream and noticed a few things that needed fixing.
1. An email change to something that actually can receive messages 
2. `pkgrel` must always start at 1 according to [Arch package guidelines](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_versioning)
3. Added new architectures to reflect the new binaries
4. The same guidelines for [Rust](https://wiki.archlinux.org/title/Rust_package_guidelines#Building) list `--locked` for building.
> fixes for AUR

- crates/bridge_harfbuzz/Cargo.toml
We need to do this to keep the crate size under the 10 MB limit. The main culprit is the test suite.
Addresses #778, hopefully.
> bridge_harfbuzz: exclude some Harfbuzz files from the Cargo package

- Cargo.lock
- Cargo.toml
- crates/geturl/src/reqwest.rs
- docs/src/howto/build-tectonic/cargo-vcpkg-dep-install.md
- docs/src/howto/build-tectonic/index.md
This may in fact be enough to fix the official Windows binaries (#780). It looks like there was a bug in `watchexec` that was recently fixed.
> Cargo.lock: update dependencies

- Cargo.toml
- crates/bridge_core/README.md
- crates/bridge_core/src/lib.rs
- docs/src/v2cli/build.md
- docs/src/v2cli/compile.md
- src/bin/tectonic/compile.rs
- src/bin/tectonic/v2cli.rs
- src/docmodel.rs
- src/driver.rs
- tests/executable.rs
In the wake of adding shell-escape support, I felt like I wanted to offer a more coherent story for users to be able to control security settings. We do this with some new security settings APIs, changing the default behavior to "untrusted" mode where known problematic features are disabled.
On the user front, in the regular `tectonic` program, insecure features will still be disabled by default. You can enable, say, shell-escape with `-Z shell-escape` as before. But now there's a `--untrusted` option that overrides any other settings and prevents shell-escape from being turned on (cf. #747).
Furthermore, the security APIs are set up in a centralized fashion such that the environment variable `$TECTONIC_UNTRUSTED_MODE` will always be honored, with the same effect as `--untrusted`.
Note …
> Add a new centralized security API

- crates/bridge_core/build.rs
- crates/bridge_flate/build.rs
- crates/engine_bibtex/build.rs
- crates/engine_xdvipdfmx/build.rs
- crates/engine_xetex/build.rs
Cf. https://github.com/tectonic-typesetting/tectonic/issues/788 . Based on my investigations, it looks like this workaround will get the main crate building on docs.rs. No way to be fully sure without making the releases and seeing what happens, though ...
> Attempt to fix the docs.rs build with CARGO_NET_OFFLINE

- Cargo.lock
- crates/bridge_core/Cargo.toml
- crates/bridge_core/README.md
- crates/bridge_core/build.rs
- crates/bridge_core/cbindgen.toml
- crates/bridge_core/support/tectonic_bridge_core_generated.h
- crates/bridge_flate/Cargo.toml
- crates/bridge_flate/README.md
- crates/bridge_flate/build.rs
- crates/bridge_flate/cbindgen.toml
- crates/bridge_flate/include/tectonic_bridge_flate.h
- crates/engine_bibtex/Cargo.toml
- crates/engine_bibtex/README.md
- crates/engine_bibtex/bibtex/bibtex_bindings.h
- crates/engine_bibtex/build.rs
- crates/engine_bibtex/cbindgen.toml
- crates/engine_xdvipdfmx/Cargo.toml
- crates/engine_xdvipdfmx/README.md
- crates/engine_xdvipdfmx/build.rs
- crates/engine_xdvipdfmx/cbindgen.toml
- crates/engine_xdvipdfmx/xdvipdfmx/xdvipdfmx_bindings.h
- crates/engine_xetex/Cargo.toml
- crates/engine_xetex/README.md
- crates/engine_xetex/build.rs
- crates/engine_xetex/cbindgen.toml
- crates/engine_xetex/src/lib.rs
- crates/engine_xetex/xetex/xetex-ini.c
- crates/engine_xetex/xetex/xetex_bindings.h
Following up on #788, my no-network workaround seemed to work OK, but then I ran into problems with `cargo metadata` wanting to create a Cargo.lock file in a read-only filesystem. I don't see any way to prevent the cbindgen build.rs invocation from triggering this.
But ... we can just use cbindgen as a standalone tool and save the generated headers in the repo. I liked the idea of doing things on-the-fly in build.rs, but I can't think of any reason that we *have* to, and the dev-time approach is faster and simpler, and it turns out that it also solves out docs.rs problems. So it's a pretty clear decision.
> Switch to dev-time rather than build-time cbindgen

- Cargo.lock
- crates/pdf_io/build.rs
Needed to keep the conda-forge package building on macOS, which is stuck on an older Rust version due to an (accidental) increase in the minimum required OS version of later releases.
I ought to define a Minimum Supported Rust Version and set up CI to monitor it, but ... not right now.
> Fix the build on Rust 1.46

- crates/engine_xetex/xetex/xetex-output.c
The `print_ln()` calls in the original code would also output newlines to the current diagnostic. Changing it to directly print newlines fixes this issue (though interestingly, the code for the `SELECTOR_TERM_AND_LOG` already did this). This change shouldn't affect the contents of the tex log, only the nicer-looking warnings that get printed to the terminal.
Fixes #684, I think, though that issue might be referring to the actual tex log that's being printed to `rust_stdout`.
> Don't wrap diagnostic warnings

- Cargo.lock
- Cargo.toml
- src/driver.rs
- src/errors.rs
- tests/executable.rs
It turns out that in some cases, biber needs access to various `.bib` files that may be associated with the document build. Fortunately, the `.run.xml` file contains exactly the information we need to populate the temporary tool directly properly. We have to link in an XML parser, but so be it.
I wasn't aware of the `.run.xml` file before and we potentially could use it a lot more aggressively. We don't do that here, but the support is written to try to be future-conscious.
Addresses #796.
> Improve biber handling by parsing the `.run.xml` file

- src/bin/tectonic/v2cli.rs
Previously the behaviour was to ignore the change while a process was
running, this also led the the bug fixed by
https://github.com/watchexec/watchexec/pull/202.
Now we queue the update so once we have finished running the commands
once we run them again.
Fixes #805
> watch: Queue updates while busy

- Cargo.lock
And update general deps while we're at it.
> Update bridge_harfbuzz's vendored source to Harfbuzz 2.9.0

- src/driver.rs
This adds a warning if the TeX pass did not produce the expected xdv file. This most commonly happens if the input document is empty.
Resolves #545.
> Add more helpful warning if xdv is missing

- crates/bridge_core/src/lib.rs
- docs/src/v2cli/compile.md
- src/driver.rs
- src/unstable_opts.rs
- tests/executable.rs
This add the `-Z search-path` option, which make tectonic look in additional paths for files.
Resolves #755.
I'm not that much of a fan of that option name (maybe something like `-Zinclude` is better?), so if you have any suggestions I'm happy to change this PR.
Todo:
> Support custom search directories

- Cargo.lock
- Cargo.toml
- crates/bridge_graphite2/build.rs
Mostly motivated by the breakage of our Windows/vcpkg CI builds.
- General deps update
- Update vendored Harfbuzz to 2.9.1
- Update to latest vcpkg
> Miscellaneous maintenance updates

- crates/pdf_io/pdf_io/dpx-jpegimage.c
This unintended fallthrough caused the JPEG decoder to issue a warning
when including a JPEG image.
Fixes #821.
> pdf_io: prevent fallthrough when reading EXIF data

- src/unstable_opts.rs
- tests/executable.rs
This is a quick hack, to error on shell-escape if an argument is given, currently it ignores any value given via `-Z shell-escape=foo`, which means if you call `-Z shell-escape=false` it is still set to true.
Rather than try and set this up to toggle the value, since that would have backwards compatibility implications, throw an error if a value is set.
I had some troubles trying to figure out here what was needed for the errmsg! macro, and ended up hacking it to just use `Err(format!`, so that might need another iteration.
The test added in the first commit fails with the current master, and should pass by the second commit.
> Shell escape arg error

- crates/cfg_support/src/lib.rs
- crates/io_base/src/filesystem.rs
- src/driver.rs
- tests/executable.rs
Fixes files used for external tools not being copied if they are located in sub directories (#843). This is done by checking the file directory against the temp directory. If they do not match, `std::fs::create_dir_all()` is used to create the directory structure for the file.
I would love to get some feedback on this implementation. Is it a decent implementation?, is it "rust-like"?, what can I change?, et cetera. It is my first time writing some rust, so I have no clue ;).
> Fix external tool file copy to include sub directories, fix #843

- crates/xdv/src/lib.rs
- docs/src/installation/index.md
- src/driver.rs
Now tectonic is available in the official repos, and tectonic-bin from the AUR is not available anymore, from the AUR only tectonic-git.
> Updating Arch Linux packages

- Cargo.lock
- Cargo.toml
- crates/engine_spx2html/Cargo.toml
OK, based on feedback, I think we have to temporarily stop using the patched Pinot.
The first version of this PR should fail with a new CI test that aims to catch the issue that I encountered.
> Avoid using patched Pinot

- crates/bundles/src/cache.rs
- docs/src/getting-started/first-document.md
- tests/cached_itarbundle.rs
Make the cache location customizable by allowing the user to overwrite it using an environment variable called `TECTONIC_CACHE_DIR`.
This fixes #880
> Make cache location customizable

- crates/bundles/src/itar.rs
- crates/engine_xetex/xetex/xetex-io.c
- tests/tex-outputs.rs
- tests/tex-outputs/pipe_input.log
- tests/tex-outputs/pipe_input.tex
I've been looking into #859 a bit. Unfortunately I don't see a super convenient way to "defuse" pipe input opens in the engine. Or, with a bit more work we *could* treat pipe opens as if they were accessing `/dev/null`, but the LaTeX3 code that's causing us problems still fails if we do so, so we're going to need to patch up the bundle anyway.
So for now, let's just add a warning message and figure out how we're going to patch the bundle.
> Warn on attempted pipe inputs

- Cargo.lock
- crates/bridge_core/src/lib.rs
- crates/bridge_core/support/support.c
- crates/bridge_core/support/tectonic_bridge_core_generated.h
- crates/bridge_flate/src/lib.rs
- crates/engine_bibtex/src/lib.rs
- crates/engine_xdvipdfmx/src/lib.rs
- crates/engine_xdvipdfmx/xdvipdfmx/dvipdfmx.c
- crates/engine_xdvipdfmx/xdvipdfmx/xdvipdfmx_bindings.h
- crates/engine_xetex/src/lib.rs
- crates/engine_xetex/xetex/xetex-engine-interface.c
- crates/engine_xetex/xetex/xetex_bindings.h
- crates/pdf_io/pdf_io/dpx-pdfobj.c
- crates/xetex_format/src/enums/dynamic.rs
- crates/xetex_layout/layout/xetex-XeTeXFontMgr_FC.cpp
- src/driver.rs
I missed a publication file when compiling a very old document using
biber.  The only error message I got was
error: not found
which isn't very helpful.  I've tried to augment the error, now it shows
error: can't open path `pub.bib`: not found
Hope this is helpful.
> Augment error message when opening files for external tools

- crates/engine_xetex/src/lib.rs
- src/driver.rs
The actual effect of the continue-on-errors option probably got lost in refactoring, see https://github.com/tectonic-typesetting/tectonic/issues/916.
A bit off topic: While investigeting, using [`into()` for `bool` to `c_int` in `xetex_engine`](https://github.com/tectonic-typesetting/tectonic/commit/bda8f7e1ec82a185bbbac55d5ddd4fd4d185eec4) popped into my mind, but I am not sure if it is actually an improvement, so I left it out of this PR. It seems to me that both my "compaction" and the previous version assume that `libc::c_int == i32`, which is mostly true, I am not sure it is a problem we should worry about.
> Use the value of the continue-on-errors option

- crates/docmodel/src/document.rs
- docs/src/v2cli/compile.md
- src/docmodel.rs
- src/driver.rs
- src/unstable_opts.rs
- tests/tex-outputs.rs
Hi
This adds support for a `-Z shell-escape-cwd=<dir>` which sets a working directory for `shell-escape` (`-Z shell-escape-cwd=$(pwd)` gives essentially the "normal" behaviour of engines for `shell-escape`). This allows using stuff like `\inputminted` (see: #835) to work the same as with other engines.
I have tested this by hand for my own use-case (#835) and it seems to work. I have not tested the toml format (because I don't use the v2 interface and couldn't get it working). I couldn't get a unit test case for it working properly though, if I run `tectonic` normally `\write18{pwd > file}` will work and send `pwd` to `file`, but when run as part of the tests it wouldn't do anything, even if I gave it an absolute path. If a test case for this is needed, I'd appreciate some pointers as to …
> Add shell escape working directory option

- Cargo.lock
- docs/src/getting-started/install.md
- docs/src/installation/index.md
Unlike https://tectonic-typesetting.github.io/install.html, here we don't have any fancy JavaScript to automatically show the right magic command.
> Update book to recommend the drop-in installers

- crates/bridge_harfbuzz/build.rs
Hopefully this should fix the conda-forge package build, which uses a pretty old SDK.
> bridge_harfbuzz: work around build failure with macOS SDK 10.9

- crates/engine_xdvipdfmx/Cargo.toml
- crates/engine_xdvipdfmx/xdvipdfmx/dvipdfmx.c
- crates/pdf_io/pdf_io/dpx-dvi.c
- crates/pdf_io/pdf_io/dpx-dvi.h
- crates/pdf_io/pdf_io/dpx-spc_pdfm.c
This code change is bigger than I anticipated, but nonetheless, here it is. I appreciate any feedback and testing (I don't use LaTeX much, so don't have real documents to test with).
Both commit messages are reproduced below.
In upstream dvipdfmx the `dvidpfmx:config` DVI special can be used to
pass arguments to dvipdfmx. This has seen some use in XeTeX packages.
For example, the ubiqitous package "hyperref" uses:
\special{dvipdfmx:config C 0x0010}
This is normally parsed by dvipdfmx as command line arguments, i.e. as
if xdvipdfmx was ran as:
xdvipdfmx -C 0x0010
The `C` option is a bitset of compatibility flags. In this case hyperref
needs the option `OPT_PDFDOC_NO_DEST_REMOVE`, which makes dvipdfmx
handle PDF destinations differently (I didn't check thoroughly how).
The `opt_flags` …
> Fix low level dvipdfmx issues

- Cargo.lock
- Cargo.toml
- crates/bridge_flate/src/lib.rs
- crates/bundles/src/cache.rs
- crates/xdv/src/lib.rs
- crates/xetex_format/src/cshash.rs
- crates/xetex_format/src/eqtb.rs
- crates/xetex_format/src/format.rs
- crates/xetex_format/src/mem.rs
- docs/src/SUMMARY.md
- docs/src/v2cli/init.md
- docs/src/v2cli/new.md
- src/bin/tectonic/v2cli.rs
- src/config.rs
- src/docmodel.rs
- src/driver.rs
- src/io/format_cache.rs
- src/test_util.rs
- tests/executable.rs
This is a simple quality of life change I would like to suggest, as it standardizes the CLI of tectonic with that of tools such as `cargo` or `poetry`. Not much else to say, tbh.
> V2 CLI: separate `new` and `init` commands

- Cargo.toml
Fixes #1030
Update to latest head revision - seems to build correctly locally.
> Bump pinned vcpkg version to fix fallout of microsoft/vcpkg#30542

- Cargo.lock
- Cargo.toml
- crates/bridge_core/Cargo.toml
- crates/bundles/Cargo.toml
- crates/docmodel/Cargo.toml
- crates/io_base/Cargo.toml
- src/config.rs
- src/driver.rs
An intermediate PR while I figure out #1033 - update all but watchexec to latest versions and run `cargo update`. This still includes a significant update for `quick-xml` to remove one of the two forward-compat warnings.
> Update non-watchexec deps

- crates/engine_bibtex/bibtex/bibtex.c
- tests/bibtex.rs
- tests/bibtex/empty/empty.blg
- tests/bibtex/mismatched_braces/expr.aux
- tests/bibtex/mismatched_braces/expr.blg
- tests/bibtex/mismatched_braces/expr.bst
- tests/bibtex/mismatched_braces/function.aux
- tests/bibtex/mismatched_braces/function.blg
- tests/bibtex/mismatched_braces/function.bst
- tests/util/mod.rs
These test some simple error cases, I plan to rebase #1032 on this so there are more tests available to avoid regressions
> Add more bibtex tests

- src/bin/tectonic/v2cli.rs
Made a mistake when updating, watchexec custom commands must be split, which to avoid implementing weird custom logic, we should treat them like a shell subcommand, not a raw exec. I also noticed the 'finished running' dialog wasn't subbing in messages anymore, it should now appear after the subprocess completes. Also tested with multiple commands and appears to work fine.
Fixes #1040
> Fix watchexec execution of custom commands

- Cargo.toml
- crates/bridge_core/src/lib.rs
- crates/xetex_layout/layout/xetex-XeTeXFontInst.cpp
- docs/src/ref/v1cli.md
- docs/src/v2cli/build.md
- docs/src/v2cli/compile.md
- docs/src/v2cli/dump.md
- src/bin/tectonic/compile.rs
- src/bin/tectonic/v2cli.rs
- src/docmodel.rs
- src/driver.rs
- src/unstable_opts.rs
I've dusted off `tectonic-on-arXiv`, and I looks like upgrading to the TeXLive 2022 bundle uncovered new reproducibility issues:
- Documents that request synctex files with `\synctex=1` contain absolute paths to the TeX files. ~~This seems intentional, so I've left absolute paths enabled for `tectonic --synctex` runs.~~
- The `hyperxmp` package embeds a bunch of metadata into the output PDF. In particular, it derives a random "xmpMM:InstanceId" from a bunch of information sources. One of those is the input file modification timestamp. I've wired this up to be the document build date instead. ~~I'm not sure if there's a "legitimate" use case for file modification timestamps, so let's just try always returning the build date instead. :slightly_smiling_face:~~
=> …
> Introduce `-Z deterministic-mode` to address a few reproducability issues

- docs/src/v2cli/build.md
- src/bin/tectonic/v2cli.rs
Solves #970.
Simple PR that checks if an optional target is specified in the build command. If yes, matches it and builds only the specific output name.
> Added ability to specify target of build

- Cargo.lock
- Cargo.toml
- crates/engine_xetex/xetex/xetex-math.c
Most important thing is to update the toplevel `Cargo.toml` to codify that the main crate will depend on a new version of `tectonic_core_bridge`, which is needed for the deterministic-output hooks introduced in #1036.
> Some release tidying

- crates/engine_bibtex/src/c_api/global.rs
Fixes #1054 
Out-of-bounds was caused because the actual global string list was being grown by `10`, not `STR_SIZE * 10`, basically.
> Grow global_str buffer by the correct amount

- src/bin/tectonic/v2cli.rs
1 line change to solve #1003.
Added quotes around exe_name to support running `watch -x` command for users with spaces in their tectonic bin location.
> added proper exe parsing for watch, supports spaces in tectonic location

- crates/bridge_core/src/lib.rs
- crates/docmodel/src/workspace.rs
- crates/io_base/src/lib.rs
- dist/azure-build-and-test.yml
- tests/bibtex.rs
- tests/executable.rs
- tests/tex-outputs.rs
- tests/trip.rs
- tests/util/mod.rs
This keeps bothering me while debugging bibtex failures, and just flipping the file order there would work, but it would be a band-aid, not a real solution. So here's a real solution - make all expectations test once, and panic once at the end.
(Also removed `genio` from bibtex tests, as it just confuses the output and all the useful logs go to both stdout and the file, IME)
> Make file expectations always check all expected files at once

- Cross.toml
- crates/engine_xetex/xetex/xetex-engine-interface.c
- dist/azure-build-and-test.yml
This includes one of the gnarliest build hacks I've ever had to perpetrate, as documented in
`crates/engine_xetex/xetex/xetex-engine-interface.c`.
xref: https://github.com/tectonic-typesetting/tectonic-ci-support/pull/24
> Add aarch64-unknown-linux-musl as a cross-buildable architecture

- docs/src/getting-started/unicode.md
destination: [tectonic/book/.../unicode.html]
[tectonic/book/.../unicode.html]: https://tectonic-typesetting.github.io/book/latest/getting-started/unicode.html#:~:text=not%20all%3A%20Unicode-,also%20broadens,-Tectonic%E2%80%99s%20the%20inputs
> docs(unicode): Fix typo

- docs/src/ref/tectonic-toml.md
The 'shell_escape_cwd' output specification is implemented, but is not documented for Tectonic.toml.
> Document 'shell_escape_cwd' for Tectonic.toml

- docs/src/ref/v2cli.md
- src/bin/tectonic/v2cli.rs
Implemented the feature proposed in #737.
Is it really that easy?
**A question:**
Should `v2_main` exit earlier if an external command is given?
We probably don't need to set up colors and customizations if we're running an external command.
> V2 CLI: Add external commands

- crates/engine_bibtex/src/xbuf.rs
Another option here might be to simply use the system allocator through `std::alloc`, at which point bibtex would actually be entirely Rust, no external links at all.
> [bibtex] Fix UB caused by invalidating protected reference

- src/bin/tectonic/compile.rs
- src/bin/tectonic/main.rs
- src/bin/tectonic/v2cli.rs
- src/config.rs
- src/docmodel.rs
- tests/executable.rs
This PR is split off from #1131. See #1131 for relevant discussions on the web bundle interface.
1. Fixes #1002: It enables us to override the default web bundle for the v2 CLI `tectonic -X new` and `tectonic -X init`, with the usual `--web-bundle` flag
2. Allows overrides: It allows user overrides of the `--web-bundle` by specifying it multiple times. The last specification of `--web-bundle` wins.
3. `tectonic -X build` is special as it never reads from the global config, but only from the local `Tectonic.toml` file, for maximal reproducibility. In this case, the global `--web-bundle` option, if specified, is ignored with a warning.
For a horrible example,
```bash
tectonic \
--web-bundle "https://this-url-gets-overridden-1" \
-X \
--web-bundle "https://this-url-gets-overridden-2" \
new \ …
```
> `--web-bundle` for v2 CLI: fix #1002 and allow overrides

- Cargo.lock
- crates/engine_spx2html/src/specials.rs
- tests/driver.rs
- tests/util/mod.rs
Sigh, I forgot that I need to put out a new release to get Linux builds using OpenSSL 3 by default. Let's see if I can get that done today.
Fortunately, with my release automation it's more a matter of checking that the CI still works, rather than jumping through the hoops of the actual release mechanics ...
> Some release prep

- crates/docmodel/src/document.rs
- crates/docmodel/src/lib.rs
- crates/docmodel/src/syntax.rs
- docs/src/getting-started/first-document.md
- docs/src/getting-started/unicode.md
- docs/src/ref/documents.md
- docs/src/ref/tectonic-toml.md
- docs/src/v2cli/init.md
- docs/src/v2cli/new.md
- src/docmodel.rs
- tests/executable.rs
This PR implements the feature detailed in #1100. Docs have been updated.
A final question I haven't had time to check:
Do all these fancy input file manipulations break latex error line numbers?
If they do, that's bad.
> Added Tectonic.toml input array

- crates/engine_bibtex/src/lib.rs
~~If you saw that master push/revert, no you didn't~~
This should supercede #1154 - on success, log files were not being closed, thus weren't getting write_digest set. See the original bibtex code at [@0.13.0/bibtex.c](https://github.com/tectonic-typesetting/tectonic/blob/tectonic%400.13.1/crates/engine_bibtex/bibtex/bibtex.c) for reference.
> Fix not closing files when spotless history is returned

- Cargo.lock
- Cargo.toml
- crates/xdv/Cargo.toml
- crates/xdv/examples/xdvdump.rs
- src/bin/tectonic/compile.rs
- src/bin/tectonic/main.rs
- src/bin/tectonic/v2cli.rs
- src/unstable_opts.rs
`structopt` has been integrated into `clap` as of `0.3`, and `atty` hasn't been updated in a few years.
This PR fixes both these problems, and closes #1034.
> Crate updates: structopt & atty

- Cargo.lock
- crates/xetex_format/Cargo.toml
- crates/xetex_format/examples/decode.rs
Changed the one remaining example that used `structopt` to use `clap` instead. This completely removes it and `atty` from our dependency tree, along with several other outdated dependencies.
> Crate update: structopt -> clap in dev-deps

- build.rs
Currently, the `tectonic` and `tectonic(bin)` targets rebuild on any change anywhere in the project, including to test files and even non-code files (changing README.md or such). This is unecessary, and caused by the build script not emitting any tracking info to Cargo, which causes it to conservatively assume rebuild on anything. We can't add a track-env on `TARGET` because that variable is set by Cargo for the build script, and tracking it will cause the same issue we're currently seeing (https://github.com/rust-lang/cargo/issues/12403 / https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-env-changed). Instead, fix the problem by tracking the build script itself, which should be what Cargo does anyways, and changing `TARGET` will always cause a rebuild no matter what …
> Don't rebuild tectonic(bin) when non-binary files are changed

- Cargo.lock
- Cargo.toml
- crates/docmodel/Cargo.toml
- dist/azure-coverage.yml
- src/bin/tectonic/v2cli/commands/watch.rs
- src/driver.rs
- tests/cached_itarbundle.rs
- tests/executable.rs
Bumps several out-of-date dependencies to the newest versions. The biggest change is `watchexec 3.0`, with `hyper 1.0` being test-only.
> Update remaining out-of-date dependencies

- src/driver.rs
Fixes #1027
tectonic did not create the subdirectories when using --keep-intermediates, now it creates them everytime.
> Create parent directories before writing files

- Cargo.lock
- Cargo.toml
- crates/bundles/src/cache.rs
- crates/docmodel/src/document.rs
- crates/engine_spx2html/src/assets.rs
- crates/engine_spx2html/src/fontfile.rs
- crates/engine_spx2html/src/fonts.rs
- crates/engine_spx2html/src/initialization.rs
- crates/engine_xetex/build.rs
- crates/io_base/src/digest.rs
- crates/xdv/src/lib.rs
- crates/xetex_layout/build.rs
- src/driver.rs
- src/io/format_cache.rs
- tests/formats.rs
- tests/util/mod.rs
Closes #1190
Closes #1184
Closes #1178
> fix: use c++ 17

- dist/azure-build-and-test.yml
CI is failing due to macos-11 having been deprecated and removed. Update to macos-12 as matching macos-latest.
> Update macos CI version to macos-12

- crates/bridge_core/src/lib.rs
- crates/docmodel/src/document.rs
- crates/docmodel/src/syntax.rs
- crates/docmodel/src/workspace.rs
- crates/engine_bibtex/src/auxi.rs
- crates/engine_bibtex/src/bibs.rs
- crates/engine_bibtex/src/bst.rs
- crates/engine_bibtex/src/log.rs
- crates/engine_bibtex/src/scan.rs
- docs/src/ref/tectonic-toml.md
- src/docmodel.rs
For context, see the discussion in #985.
Closes #985.
This PR adds an `extra_paths` config key that allows a user to specify external resources.
An example file tree and `Tectonic.toml` are below.
```toml
[doc]
name = "Test"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"
extra_paths = [
"../../resources"
]
[[output]]
name = "main"
type = "pdf"
```
```
workspace-repo-root/
├── resources/
│   └── class files, etc      <-- All documents pull files from here
│
├── Subdir1/
│   ├── this document/
│   │   ├── src/
│   │   └── Tectonic.toml     <-- this file is above
│   └── more documents...
│   
└── Subdir2/
   └── and so on...
```
> Extra paths for shared resources

- Cargo.lock
- Cargo.toml
- docs/src/ref/v2cli.md
- src/bin/tectonic/compile.rs
- src/bin/tectonic/v2cli/commands/show.rs
- tests/executable.rs
This is made possible by recent cleanups #1162, #1167, #1169 of the cli implementations. Thank you all! @rm-dr @CraftSpider 
The completions are generated by `clap_complete`. The current v1 & v2 cli mixture makes it a bit difficult to offer clean completions for the `tectonic` command, so for now we only target the `nextonic` command exclusively for the v2 cli. To print the shell completions, simply run:
```bash
tectonic -X show shell-completions zsh # or bash, or your favorite <SHELL>
```
> Generate shell completions for `nextonic`

- src/driver.rs
Fixes #1149.
The MR applies the fix as described in https://github.com/tectonic-typesetting/tectonic/issues/1149#issuecomment-1943822679.
I added also added some error reporting around the call of std::fs::create_dir_all.
> shell escape: fixes creation of temporary subdirectories

- crates/docmodel/src/document.rs
- crates/docmodel/src/syntax.rs
- docs/src/ref/tectonic-toml.md
- src/docmodel.rs
- tests/synctex/Tectonic.toml
- tests/synctex/src/_postamble.tex
- tests/synctex/src/_preamble.tex
- tests/synctex/src/index.tex
This closes #889. It adds the option `synctex = bool` to create the files needed by synctex.
This PR also adds : 
- A few tests of the synctex option in toml.
- A functional test in tests/synctex
- A line of documentation in the tectonic book
> Add synctex option in Toml file

- crates/bridge_flate/src/lib.rs
- crates/bundles/src/itar.rs
- crates/bundles/src/ttb_fs.rs
- crates/bundles/src/ttb_net.rs
- crates/engine_bibtex/src/auxi.rs
- crates/engine_bibtex/src/bibs.rs
- crates/engine_bibtex/src/bst.rs
- crates/engine_bibtex/src/char_info.rs
- crates/engine_bibtex/src/cite.rs
- crates/engine_bibtex/src/entries.rs
- crates/engine_bibtex/src/exec.rs
- crates/engine_bibtex/src/hash.rs
- crates/engine_bibtex/src/pool.rs
- crates/engine_bibtex/src/scan.rs
- crates/engine_spx2html/src/fonts.rs
- crates/engine_spx2html/src/lib.rs
- crates/engine_spx2html/src/specials.rs
- crates/io_base/src/stack.rs
- src/bin/tectonic/v2cli/mod.rs
- src/errors.rs
- tests/formats.rs
- tests/util/mod.rs
> Use `i64` to prevent overflows

- src/bin/tectonic/v2cli/commands/watch.rs
Make watchexec shutdown gracefully on ctrl-C, and make sure new jobs are started, not just existing ones.
Fixes #1213
Fixes #1237
> Fix multiple watchexec issues

- crates/engine_bibtex/src/exec.rs
- tests/bibtex.rs
- tests/bibtex/alpha.bst
- tests/bibtex/cites/control_seq.aux
- tests/bibtex/cites/control_seq.bbl
- tests/bibtex/cites/control_seq.bib
- tests/bibtex/cites/control_seq.blg
- tests/bibtex/cites/control_seq_alpha.aux
- tests/bibtex/cites/control_seq_alpha.bbl
- tests/bibtex/cites/control_seq_alpha.blg
- tests/bibtex/cites/multi_file.aux
- tests/bibtex/cites/multi_file.bbl
- tests/bibtex/cites/multi_file.blg
- tests/bibtex/cites/multi_file_1.bib
- tests/bibtex/cites/multi_file_2.bib
More tests extracted from work in #1163
Also fixes #1185 by adding a missing `idx += 1`
> Add multi-file and control-sequence tests for Bibtex

- dist/azure-build-and-test-vcpkg.yml
- dist/azure-build-and-test.yml
Cache is per-target, and will be invalidated by changes to Cargo.toml, so vcpkg metadata changes should invalidate it.
Fixes #1255
> Cache vcpkg build to improve CI speed

- dist/azure-build-and-test-pkgconfig.yml
- dist/azure-build-and-test.yml
Windows 2019 images are going away at the end of the month. Update early.
> Bump to windows 2022

- Cargo.lock
- crates/bridge_harfbuzz/Cargo.toml
- crates/bridge_harfbuzz/build.rs
This fixes the issue for me on a mac with external-harfbuzz enabled. This is a bit of a hack, but should only apply to the very specific case we're worried about.
Fixes #1272
> Add workaround for mac external-harfbuzz issues

- src/bin/tectonic/v2cli/commands/watch.rs
This fixes a problem with the watch command when using v2 cli with a symlink named `nextonic` .
> Fix v2 cli flag being incorrectly applied

- crates/docmodel/src/document.rs
- crates/docmodel/src/syntax.rs
Hello!
When introducing the `inputs` config key in #1123, the default behavior when none of the `inputs`, `preamble`, `index` and `postamble` key is given has been changed to use an empty list instead of the `DEFAULT_INPUTS` new default `const`. Reading the PR discussions, i saw that you wanted to keep backward compatibility, so i guess it's a bug.
i see a few ways to get backward compatibility back, i picked one that requires re-adding the `DEFAULT_INDEX_FILE`, `DEFAULT_PREAMBLE_FILE` and `DEFAULT_POSTAMBLE` `const` to be used when no `inputs` is given, i think this is the simplest way to get the exact same behavior, despite it not being the cleanest.
i also added a non-regression test for good measure.
> Fixed a regression brought in #1123

- codecov.yml
- dist/azure-coverage.yml
- tests/executable.rs
`cargo kcov` has not recieved updates in years, and has increasingly many incompatibilities. Instead of adding more hacks, switch to a coverage tool that:
A) Is regularly updated
B) Is simpler to use
C) Provides more detailed coverage statistics
D) Halves the runtime of the coverage pipeline
> Switch to using llvm-cov

- .github/actions/build-setup/action.yml
- .github/actions/deploy-setup/action.yml
This should fix it not being found in the release workflow
> Use same name for release bundle everywhere

- .github/actions/build-setup/action.yml
- .github/workflows/build_and_test.yml
- .github/workflows/prep.yml
Follow up to #1294. This adds warning/error annotations and moves jobs that don't need setup to `prep`.
> GitHub Actions Improvements

- .github/actions/build-setup/action.yml
Now that https://github.com/pkgw/cranko/pull/53 has merged, we should be able to speed up this step.
> Switch mac setup to use precompiled cranko

- Cargo.toml
gperf:arm64-osx was failing on macOS due to an outdated vcpkg port definition; see e.g. https://github.com/tectonic-typesetting/tectonic/actions/runs/17890169920/job/50869494362. This bump should hopefully fix the build.
> chore: bump vcpkg ref, maybe fix gperf build
