src/io/itarbundle.rs

* Add 'please' to make the error mesage on overall network failure more
polite.
Signed-off-by: mr.Shu <mr@shu.io>

src/io/itarbundle: More polite network error msg

---

Cargo.lock
src/io/mod.rs

Fix certain PDF images

---

.travis.yml

I think the best fix to #144 is to backport newer harfbuzz to xenial.

Attempt to fix the Travis CI Linux build.

---

README.md

[Rendered](https://github.com/Mrmaxmeier/tectonic/blob/ae40ab704e0403be903c4d4483adea2667c025da/README.md)

Add packaging status badge

---

src/cli_driver.rs
src/driver.rs
src/errors.rs
src/io/setup.rs
src/lib.rs

This moves ProcessingSession and some related structs to the main tectonic crate.

Move ProcessingSession to the main crate.

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/cli_driver.rs
xdv/Cargo.toml

Let's check that it passes CI.

Candidate version 0.1.8.

---

Cargo.lock

Rolls up various dependabot PRs.

Cargo.lock: update various deps

---

CHANGELOG.md
Cargo.lock
Cargo.toml
tectonic/io.c
xdv/Cargo.toml

Candidate bits for version 0.1.10.

Version 0.1.10

---

tectonic/dpx-spc_dvips.c

It all relies on farming work out to Ghostscript, as far as I can tell. We don't want that.
(Unfortunately the diff looks terrible because I reindented, but basically all this does is delete a lot of code.)

Remove PSTricks functionality

---

CHANGELOG.md
Cargo.lock
Cargo.toml
dist/arch/PKGBUILD
xdv/Cargo.toml

From hell's heart I stab at thee, purl.org SSL certificate! :whale:

Release 0.1.11

---

.gitignore
dist/appimage/Makefile
dist/appimage/tectonic.desktop
dist/appimage/tectonic.svg

Ref: #280 
I add Makefile and some resource to build AppImage of tectonic.
Thank you for agreement to add AppImage.
Cheers!

Make AppImage

---

.travis.yml

I'm going to start by submitting this as a PR which should *not* cause anything to happen. Then we'll see what happens if/when this is merged to master.

.travis.yml: experiment with "releasing" an AppImage every time we build on master

---

src/engines/mod.rs
src/engines/spx2html.rs
src/io/filesystem.rs
src/io/format_cache.rs
src/io/itarbundle.rs
src/io/local_cache.rs
src/io/mod.rs

Fixes [`identity_conversion`](https://rust-lang.github.io/rust-clippy/master/#identity_conversion).

cargo clippy: fix identity_conversion

---

src/engines/bibtex.rs
src/engines/mod.rs
src/engines/spx2html.rs
src/engines/xdvipdfmx.rs
src/io/stdstreams.rs
src/status/mod.rs

Fixes [`new_without_default`](https://rust-lang.github.io/rust-clippy/master/index.html#new_without_default)

cargo clippy: fix new_without_default

---

src/errors.rs

Silence error-chain deprecation warnings

---

src/app_dirs.rs
src/config.rs
src/lib.rs

This makes it easier to customize the app dirs.

Encapsulate app_dirs usage

---

src/bin/tectonic.rs
tests/formats.rs

More of af8ccfcc223957d3ed1b3275e9ec4ac17635c1e3

update comment references to the CLI

---

docs/src/introduction/index.md

Saw a typo, ended up revising the structure a bit.

docs/src/introduction/index.md: revise

---

src/driver.rs

Currently tectonic prints "warnings were issued ..." warning only the first time the tex engine pass has warnings. However, this is not very useful since we expect warnings in the early passes due to missing references etc. What one cares about is whether the last pass has any warnings.
This commit updates the logic so that only the warnings from the very last pass are reported.
As a minor change, I introduced an enum `RerunReason` to avoid stringly typing it.

Warnings during the last pass only

---

CHANGELOG.md
Cargo.lock
Cargo.toml
cfg_support/Cargo.toml
cfg_support/README.md
dist/arch/PKGBUILD
dist/build-mdbook.sh
xdv/Cargo.toml

At long last, putting the next release into motion. Check out the monster changelog @efx @malbarbo @Mrmaxmeier @ratmice @rekka @spl !

Release 0.1.12

---

.azure-pipelines/cross-build-job.yml
.azure-pipelines/pr-pipeline.yml
Cross.toml
tests/executable.rs

Azure pipelines, take 2

---

.azure-pipelines/variables.yml
Cross.toml
build.rs
tests/executable.rs

Start CI/CD-ing on mips-unknown-linux-gnu

---

README.md

README.md: mention the new GitHub action and tt.ente.ninja

---

tectonic/xetex-XeTeXFontMgr_FC.cpp

Guard against potential segfault

---

src/lib.rs

Test for #606, sorry for the delay

Add regression test for previously fixed crash

---

dist/arch/deploy.sh
dist/azure-ci-cd.yml
dist/azure-deployment-setup.yml
dist/azure-deployment.yml

I realized that our deployment stage can be a bunch of parallel jobs, not just one serial script, which should be very helpful.

And yet more CI/CD improvement

---

src/engines/mod.rs

As reported in #669, the `lipsum` package is currently broken in TeXLive 2020 because it requests the file `lipsum.ltd.tex` under the name `lipsum.ltd`. At the moment, our file lookup code doesn't try alternative extensions (e.g., adding `.tex`) if the input filename has an extension. Alter this behavior to try adding a new extension, such that `lipsum` should start working again.
I think that this change should, if anything, fix other packages that have been problematic, but we'll have to see what @Mrmaxmeier's tool and my bundle tests report.

src/engines: fix `lipsum` in TeXLive 2020

---

src/engines/mod.rs
src/io/mod.rs

It seems that in some esoteric cases, there are TeX files that are read-then-written from one run to another, but they are only partially read. Because our rerun-detection logic compares what was read to what was written, this sort of incomplete reading triggers a rerun loop.
Here we attempt to fix that by scanning through any remaining unread data when closing an input file and updating the digest if needed. This would also yield the right results for the common TeX pattern of opening an input file and immediately closing it, which we had to special-case before.
Closes #679.

src/engines: incorporate remaining data into digest when closing input files

---

Cargo.lock
Cargo.toml
src/io/stdstreams.rs

Dependabot was busy this week!

Dependabot rollup and Clippy fix

---

dist/arch/PKGBUILD.bin.in
dist/arch/PKGBUILD.src.in
dist/arch/deploy.sh

Closes #700.
CC @lmartinez-mirror

dist/arch: update the tectonic-bin package as well

---

crates/bridge_flate/build.rs
docs/src/SUMMARY.md
docs/src/getting-started/first-document.md
docs/src/v2cli/compile.md
src/engines/mod.rs

Mainly motivated by a clippy failure that somehow snuck in, but also fixing a few other small issues.
Closes #735.

Miscellaneous small fixes

---

Cargo.lock
crates/bridge_core/Cargo.toml
crates/bridge_core/src/lib.rs
crates/bridge_graphite2/src/lib.rs
crates/engine_bibtex/Cargo.toml
crates/engine_bibtex/src/lib.rs
crates/engine_xdvipdfmx/Cargo.toml
crates/engine_xdvipdfmx/src/lib.rs
crates/engine_xdvipdfmx/xdvipdfmx/dvipdfmx.c
crates/engine_xetex/Cargo.toml
crates/engine_xetex/README.md
crates/engine_xetex/src/lib.rs
crates/geturl/src/lib.rs
crates/io_base/src/lib.rs
crates/pdf_io/Cargo.toml
crates/pdf_io/README.md
crates/pdf_io/src/lib.rs
crates/xetex_layout/Cargo.toml
crates/xetex_layout/src/lib.rs
src/driver.rs
src/engines/bibtex.rs
src/engines/tex.rs
src/engines/xdvipdfmx.rs
src/lib.rs
tests/formats.rs
tests/tex-outputs.rs
tests/trip.rs
tests/util/mod.rs

They now all `deny(missing_docs)`, and I've tried to tidy up some API warts.

Tidy up a lot of the new crates

---

crates/engine_xetex/src/lib.rs
crates/engine_xetex/xetex/xetex-ext.c
crates/engine_xetex/xetex/xetex-ext.h
crates/engine_xetex/xetex/xetex-ini.c
src/lib.rs
tests/formats.rs

Fix \XeTeXfeaturename and a few other issues

---

crates/bridge_core/build.rs
crates/bridge_flate/build.rs
crates/engine_bibtex/build.rs
crates/engine_xdvipdfmx/build.rs
crates/engine_xetex/build.rs
crates/io_base/src/lib.rs
dist/arch/deploy.sh

Some small stuff, bundled up to save on CI time.

Miscellaneous fixes

---

Cargo.lock
crates/bridge_flate/build.rs

Looks like we need to set `CARGO_NET_OFFLINE=true`, not `CARGO_NET_OFFLINE=1`.

bridge_flate cbindgen take two

---

docs/src/installation/index.md

related discussion: https://discourse.nixos.org/t/nix-not-nixos-error-attribute-nixos-in-selection-path/8339/3

nix installation has deprecated method

---

Cargo.lock
Cargo.toml
crates/bundles/src/cache.rs
crates/bundles/src/itar.rs
crates/pdf_io/pdf_io/dpx-cmap_write.c
crates/pdf_io/pdf_io/dpx-pdfobj.c
docs/src/SUMMARY.md
docs/src/v2cli/dump.md
src/bin/tectonic/compile.rs
src/bin/tectonic/v2cli.rs
tests/cached_itarbundle.rs
tests/executable.rs

This is intended to be the recommended way for external tools to see what's going on inside a Tectonic document build.

Add the `tectonic -X dump` command

---

src/bin/tectonic/v2cli.rs

fix: v2 cli watch on windows failed 

---

Cargo.lock
crates/engine_xetex/xetex/xetex-xetex0.c

Tidy up this bonkers function and start using symbolic constants for the main command dispatch. Also update deps.

Symbolic main_control

---

Cargo.lock
crates/engine_spx2html/src/font.rs
crates/geturl/src/reqwest.rs
crates/xetex_format/src/dimenpars.rs
crates/xetex_format/src/enums/dynamic.rs
crates/xetex_format/src/etexpenalties.rs
crates/xetex_format/src/gluepars.rs
crates/xetex_format/src/intpars.rs
crates/xetex_format/src/locals.rs
src/driver.rs
src/io/format_cache.rs
tests/executable.rs

I let this linger for far too long, but I think I have a good fix and test case now.

Fix issue 844

---

Cargo.toml
dist/azure-build-and-test-vcpkg.yml
src/bin/tectonic/main.rs
tests/executable.rs

See #874 . Hope this is enough!

src/bin/tectonic/main.rs: -X option in CLI docs

---

Cargo.lock

No specific known reason to upgrade, but I want to stay up-to-date as much as possible.

Update to Harfbuzz 4.4.0

---

crates/io_base/src/filesystem.rs

I would like to get some of the changes proposed by @ralismark in #806 into the codebase, but that PR has been idle for a while. I'm going to supersede it with this pared-down version.

Warn when opening absolute paths (pared down version of #806)

---

Cargo.lock
Cargo.toml
dist/azure-build-and-test-vcpkg.yml
dist/azure-build-and-test.yml

Update to Harfbuzz 5.2.0, and also update Cargo deps.

Harfbuzz 5.2.0

---

crates/engine_spx2html/src/lib.rs

See issue #954. We shouldn't panic! And we also now try to print a warning that will hopefully be helpful.

engine_spx2html: fix up behavior when compiling un-customized documents

---

Cargo.toml
dist/azure-build-and-test-vcpkg.yml
dist/azure-build-and-test.yml
dist/azure-generic-build.yml

dist: first attempt at darwin-aarch64 build support

---

crates/docmodel/src/document.rs

docmodel: have `shell_escape_cwd` imply `shell_escape = true`

---

Cargo.lock

Update vendored Harfbuzz to 7.3.0, and update Cargo deps

---

crates/engine_spx2html/src/emission.rs

Some issues I noticed today while doing some Tectonopedia work.

Squeeze in a couple of HTML fixes

---

README.md
docs/src/index.md

It seems from #766 and #878 that the old forums are being sunsetted, so this PR completes the cutoff from them.

Update forum links

---

Cargo.lock
crates/xetex_format/src/symbols.rs
docs/src/installation/index.md
src/driver.rs

Update Arch Linux package URL in index.md

---

crates/bridge_harfbuzz/build.rs

Fix install error, when harfbuzz folder is not created

---

dist/azure-generic-build.yml
src/errors.rs
tests/bibtex.rs
tests/tex-outputs.rs
tests/trip.rs
tests/util/mod.rs

Various changes I've thought of that would improve the testing/debugging experience while developing. There's at least one more to come, hopefully - improved differences on binary files such as XDV and PDF. The Azure pipelines thing is the most important one though, and the others were fast, so I figured best to get this in now.

Improve testing infrastructure

---

.gitignore
bundles/bundles/texlive2024-0312/bundle.toml
bundles/bundles/texlive2024-0312/include/tectonic/tectonic-format-latex.tex
bundles/bundles/texlive2024-0312/include/tectonic/tectonic-format-plain.tex
bundles/bundles/texlive2024-0312/patches/texlive/fithesis-mu-base.sty.diff
bundles/bundles/texlive2024-0312/patches/texlive/fontawesome.sty.diff
bundles/bundles/texlive2024-0312/patches/texlive/latex.ltx.diff
bundles/bundles/texlive2024-0312/patches/texlive/listings.sty.diff
src/bin/tectonic/v2cli/commands/bundle/actions.rs
src/bin/tectonic/v2cli/commands/bundle/select/picker.rs

Add texlive2024 bundle

---

crates/docmodel/src/syntax.rs

Silly change that's messing up CI

Run format

---

dist/azure-build-and-test-pkgconfig.yml
dist/azure-build-and-test.yml

macos-12 has been retired by Azure, bump to macos-13

Update macos version

---

Cargo.toml
crates/engine_bibtex/src/log.rs
crates/engine_spx2html/src/fonts.rs
crates/geturl/src/reqwest.rs
crates/io_base/src/lib.rs

Hopefully this will fix the MSVC issues. Will also fix Clippy now

Update vcpkg ref

---

crates/xdv/src/lib.rs

Don't use cast_signed yet

---

Cargo.lock
codecov.yml
crates/bridge_freetype2/Cargo.toml
crates/bridge_freetype2/build.rs
crates/bridge_freetype2/src/lib.rs
crates/bridge_freetype2/src/sys.rs

Another part of #1138 - split out and improved with docs and tests

Add Rust bindings to FreeType2

---

.github/actions/build-and-test/action.yml
.rustfmt.toml
Cargo.toml
crates/bridge_core/Cargo.toml
crates/bridge_flate/Cargo.toml
crates/bridge_fontconfig/src/pat.rs
crates/bridge_graphite2/Cargo.toml
crates/bridge_harfbuzz/Cargo.toml
crates/bridge_icu/Cargo.toml
crates/bundles/Cargo.toml
crates/cfg_support/Cargo.toml
crates/dep_support/Cargo.toml
crates/dep_support/src/lib.rs
crates/docmodel/Cargo.toml
crates/engine_bibtex/Cargo.toml
crates/engine_bibtex/src/pool.rs
crates/engine_spx2html/Cargo.toml
crates/engine_xdvipdfmx/Cargo.toml
crates/engine_xetex/Cargo.toml
crates/engine_xetex/src/lib.rs
crates/errors/Cargo.toml
crates/geturl/Cargo.toml
crates/io_base/Cargo.toml
crates/pdf_io/Cargo.toml
crates/status_base/Cargo.toml
crates/xdv/Cargo.toml
crates/xetex_format/Cargo.toml
crates/xetex_layout/Cargo.toml
tests/executable.rs
tests/util/mod.rs

We recently hit edition 2024, and our MSRV is generally only around N-3. So time to bump this.

Update edition to 2021

---

crates/xdv/src/lib.rs

Just run through tex-outputs and parse them all. This doesn't really ensure it all parses _correctly_, but it ensures that everything we output is well-formed / the parser can handle all directives we output.

Add simple test to xdv crate to ensure all outputs parse
